# -*- coding: utf-8 -*-
"""heterogeneity_analysis_COLAB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/151I9wrXwUFCNdqTWr4zXAiH_AHdjhofA

# Intra-Tumor Heterogeneity Analysis
**Central vs. Peripheral CoLIAGe Radiomic Features — PDAC Cases**

Runs Step C for each internal fraction in {0.4, 0.5, 0.6}.

Each fraction produces its own set of results in a dedicated subfolder:
```
OUTPUT_BASE_DIR/
  fraction_0.4/   plots/ + CSVs
  fraction_0.5/   plots/ + CSVs
  fraction_0.6/   plots/ + CSVs
  comparison/     cross-fraction comparison plots
```
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import ttest_rel, wilcoxon, pearsonr, spearmanr
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# ── CELL 1: Mount Google Drive ────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive', force_remount=False)

# Base directory that contains AGGREGATED_BASE/
#     fraction_0.4/  X_central.npy  X_peripheral.npy  X_heterogeneity.npy  case_ids.npy
#     fraction_0.5/  ...
#     fraction_0.6/  ...

FRACTIONS = [0.6] #[0.4, 0.5, 0.6]
AGGREGATED_BASE = f"/content/drive/MyDrive/intra_tumor_heterogen_589/aggregated_{FRACTIONS}"
OUTPUT_BASE_DIR = f"/content/drive/MyDrive/intra_tumor_heterogen_589/aggregated_{FRACTIONS}/analysis_res"
os.makedirs(OUTPUT_BASE_DIR, exist_ok=True)
print('Config set.')
print(f'Aggregated base : {AGGREGATED_BASE}')
print(f'Output base     : {OUTPUT_BASE_DIR}')
print(f'Fractions       : {FRACTIONS}')

tumor_volumes = np.load("/content/drive/MyDrive/intra_tumor_heterogen_589/aggregated_0.6/tumor_volumes_0.6.npy")
tumor_volumes.shape

# Κράτα ΜΟΝΟ όσους είναι μεγαλύτεροι από 0 (θα μείνουν ακριβώς 462)
valid_mask = tumor_volumes > 0
volumes = tumor_volumes[valid_mask]
volumes.shape

"""# ── 3. Imports"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from scipy.stats import ttest_rel, wilcoxon, pearsonr, spearmanr
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# %matplotlib inline
plt.rcParams['figure.dpi'] = 120
plt.rcParams['font.size']  = 10

# ── CELL 4: Feature names — 13 Haralick × 2 angles = 26 channels ─────────────
HARALICK_BASE = [
    'AngularSecondMoment', 'Contrast', 'Correlation',
    'SumOfSquaresVariance', 'SumAverage', 'SumVariance', 'SumEntropy',
    'Entropy', 'DifferenceVariance', 'DifferenceEntropy',
    'InfoMeasureCorr1', 'InfoMeasureCorr2', 'MaximalCorrelationCoeff',
]
FEATURE_NAMES = (
    [f'{f}_Primary'   for f in HARALICK_BASE] +
    [f'{f}_Secondary' for f in HARALICK_BASE]
)
assert len(FEATURE_NAMES) == 26
print(f'Feature names: {len(FEATURE_NAMES)} (13 Haralick × 2 angles)')

"""# ── CELL 5: Helper functions"""

def load_fraction_data(fraction):
    """Load aggregated arrays for a given fraction. Drops CT channel if present."""
    frac_str = f'fraction_{fraction}'
    # The AGGREGATED_BASE is already set to the specific fraction's aggregated data folder.
    # So, we should use AGGREGATED_BASE directly, not join an additional frac_str subfolder.
    frac_dir = AGGREGATED_BASE

    # Support both naming conventions
    def try_load(names):
        for name in names:
            p = os.path.join(frac_dir, name)
            if os.path.exists(p):
                return np.load(p)
        raise FileNotFoundError(f'None of {names} found in {frac_dir}')

    central    = try_load(['X_central.npy',      'central_vectors.npy'])
    peripheral = try_load(['X_peripheral.npy',   'peripheral_vectors.npy'])
    heterog    = try_load(['X_hetero.npy','heterogeneity_vectors.npy'])
    case_ids   = np.load(os.path.join(frac_dir, 'case_ids.npy'), allow_pickle=True)

    # Drop CT intensity channel (index 0) if 27 features present
    for arr_name, arr in [('central', central), ('peripheral', peripheral), ('heterogeneity', heterog)]:
        if arr.shape[1] == 27:
            pass  # handled below
    if central.shape[1] == 27:
        central    = central[:, 1:]
        peripheral = peripheral[:, 1:]
        heterog    = heterog[:, 1:]
        print(f'  [{frac_str}] Dropped CT channel — keeping 26 Haralick features.')

    assert central.shape[1] == 26, f'Expected 26 features, got {central.shape[1]}'

    # Optional tumor volumes
    vol_path = os.path.join(frac_dir, f'tumor_volumes_{fraction}.npy')
    volumes  = np.load(vol_path).astype(np.float32) if os.path.exists(vol_path) else None

    print(f'  [{frac_str}] Loaded {len(case_ids)} cases, '
          f'volumes={"yes" if volumes is not None else "no"}')
    return central, peripheral, heterog, case_ids, volumes

print('Helpers defined.')

def apply_bonferroni(p_values, n_tests=None):
    n = n_tests or len(p_values)
    return np.clip(np.array(p_values) * n, 0, 1)

def cohens_d_paired(a, b):
    diff = a - b
    return diff.mean() / (diff.std(ddof=1) + 1e-12)

def save_fig(fig, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fig.savefig(path, dpi=150, bbox_inches='tight')
    plt.show()
    print(f'  Saved → {path}')

"""# Analysis functions"""

def run_paired_tests(central, peripheral, out_dir):
    """Paired t-test + Wilcoxon per feature with Bonferroni correction."""
    n_feat   = len(FEATURE_NAMES)
    results  = []
    for i, fname in enumerate(FEATURE_NAMES):
        c = central[:, i]
        p = peripheral[:, i]
        valid = np.isfinite(c) & np.isfinite(p)
        c, p  = c[valid], p[valid]
        t_stat, p_t = ttest_rel(c, p)
        try:
            w_stat, p_w = wilcoxon(c - p)
        except ValueError:
            w_stat, p_w = np.nan, np.nan
        results.append({
            'feature': fname, 'n_valid': int(valid.sum()),
            'mean_central': c.mean(), 'mean_peripheral': p.mean(),
            'mean_diff': (c-p).mean(), 'std_diff': (c-p).std(ddof=1),
            'cohens_d': cohens_d_paired(c, p),
            't_stat': t_stat, 'p_ttest_raw': p_t,
            'w_stat': w_stat, 'p_wilcox_raw': p_w,
        })
    df = pd.DataFrame(results)
    df['p_ttest_bonf']  = apply_bonferroni(df['p_ttest_raw'].values,  n_feat)
    df['p_wilcox_bonf'] = apply_bonferroni(df['p_wilcox_raw'].fillna(1).values, n_feat)
    df['sig_ttest']  = df['p_ttest_bonf']  < 0.05
    df['sig_wilcox'] = df['p_wilcox_bonf'] < 0.05
    df = df.sort_values('p_ttest_bonf')

    n_sig = int(df['sig_ttest'].sum())
    print(f'  Significant features (Bonferroni t-test): {n_sig}/{n_feat}')
    df.to_csv(os.path.join(out_dir, 'paired_tests.csv'), index=False)

    # Plot
    fig, ax = plt.subplots(figsize=(14, 8))
    log_p   = -np.log10(df['p_ttest_bonf'].clip(lower=1e-10))
    colors  = ['tomato' if s else 'steelblue' for s in df['sig_ttest']]
    ax.barh(df['feature'], log_p, color=colors, edgecolor='none')
    ax.axvline(-np.log10(0.05), color='black', linestyle='--',
               linewidth=1.2, label='p=0.05 (Bonferroni)')
    ax.set_xlabel('-log₁₀(Bonferroni p-value)', fontsize=11)
    ax.set_title('Central vs. Peripheral — Feature Significance\n'
                 '(red = significant, α=0.05 Bonferroni)', fontsize=12, fontweight='bold')
    ax.tick_params(axis='y', labelsize=8)
    ax.legend(fontsize=9)
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '01_significance.png'))
    return df


def plot_distributions(central, peripheral, out_dir):
    """Per-feature overlaid histograms: central vs peripheral."""
    n_cols = 4
    n_rows = (len(FEATURE_NAMES) + n_cols - 1) // n_cols
    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols*4, n_rows*3))
    axes = axes.flatten()
    for i, fname in enumerate(FEATURE_NAMES):
        ax = axes[i]
        ax.hist(central[:, i],    bins=25, alpha=0.6, color='steelblue',
                label='Central',    density=True)
        ax.hist(peripheral[:, i], bins=25, alpha=0.6, color='darkorange',
                label='Peripheral', density=True)
        ax.set_title(fname, fontsize=7, fontweight='bold')
        ax.tick_params(labelsize=6)
        if i == 0:
            ax.legend(fontsize=6)
    for j in range(i+1, len(axes)):
        axes[j].axis('off')
    plt.suptitle('Feature Distributions — Central vs. Peripheral (PDAC)\n', fontsize=12, fontweight='bold')
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', f'02_distributions_{FRACTIONS}.png'))


def analyse_magnitude(heterog, out_dir):
    """L2 norm of the heterogeneity vector per case."""
    magnitudes = np.linalg.norm(heterog, axis=1)
    stats = {
        'n_cases': len(magnitudes),
        'mean':    magnitudes.mean(),
        'std':     magnitudes.std(ddof=1),
        'median':  float(np.median(magnitudes)),
        'q25':     float(np.percentile(magnitudes, 25)),
        'q75':     float(np.percentile(magnitudes, 75)),
        'min':     float(magnitudes.min()),
        'max':     float(magnitudes.max()),
    }
    print(f'  Mean magnitude: {stats["mean"]:.4f} ± {stats["std"]:.4f}')
    pd.DataFrame([stats]).to_csv(
        os.path.join(out_dir, 'magnitude_stats.csv'), index=False)

    fig, axes = plt.subplots(1, 2, figsize=(13, 5))
    axes[0].hist(magnitudes, bins=30, color='mediumpurple',
                 edgecolor='white', alpha=0.85)
    axes[0].axvline(magnitudes.mean(), color='tomato', linestyle='--',
                    linewidth=1.8, label=f'Mean={magnitudes.mean():.3f}')
    axes[0].axvline(float(np.median(magnitudes)), color='navy', linestyle=':',
                    linewidth=1.8, label=f'Median={float(np.median(magnitudes)):.3f}')
    axes[0].set_xlabel('Heterogeneity Magnitude (L2 norm)')
    axes[0].set_ylabel('Count')
    axes[0].set_title('Distribution of Intra-Tumor Heterogeneity')
    axes[0].legend(fontsize=9)

    sorted_mag = np.sort(magnitudes)
    axes[1].plot(sorted_mag, color='mediumpurple', linewidth=1.5)
    axes[1].fill_between(range(len(sorted_mag)), sorted_mag,
                         alpha=0.2, color='mediumpurple')
    axes[1].set_xlabel('Case rank (sorted)')
    axes[1].set_ylabel('Heterogeneity Magnitude')
    axes[1].set_title('Sorted Magnitudes — each point = one PDAC case')

    plt.suptitle('Intra-Tumor Heterogeneity Magnitude', fontsize=12, fontweight='bold')
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '03_magnitude.png'))
    return magnitudes


def run_pca(heterog, out_dir):
    """PCA on the heterogeneity vectors."""
    scaler   = StandardScaler()
    H_scaled = scaler.fit_transform(heterog)
    n_comp   = min(10, H_scaled.shape[1])
    pca      = PCA(n_components=n_comp)
    coords   = pca.fit_transform(H_scaled)
    explained  = pca.explained_variance_ratio_
    cumulative = np.cumsum(explained)

    print(f'  PC1={explained[0]*100:.1f}%  PC1+PC2={cumulative[1]*100:.1f}%  '
          f'n_for_80%={int(np.searchsorted(cumulative, 0.80))+1}')

    pd.DataFrame(pca.components_.T,
                 index=FEATURE_NAMES,
                 columns=[f'PC{i+1}' for i in range(n_comp)]
                 ).to_csv(os.path.join(out_dir, 'pca_loadings.csv'))

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].bar(range(1, len(explained)+1), explained*100,
                color='steelblue', alpha=0.8, label='Individual')
    axes[0].step(range(1, len(cumulative)+1), cumulative*100,
                 color='tomato', linewidth=2, label='Cumulative')
    axes[0].axhline(80, color='gray', linestyle='--', linewidth=1,
                    alpha=0.7, label='80% threshold')
    axes[0].set_xlabel('Principal Component')
    axes[0].set_ylabel('Explained Variance (%)')
    axes[0].set_title('PCA Scree Plot')
    axes[0].legend(fontsize=9)
    axes[0].set_xticks(range(1, len(explained)+1))

    axes[1].scatter(coords[:, 0], coords[:, 1],
                    alpha=0.45, s=18, color='mediumpurple', edgecolors='none')
    axes[1].set_xlabel(f'PC1 ({explained[0]*100:.1f}%)')
    axes[1].set_ylabel(f'PC2 ({explained[1]*100:.1f}%)')
    axes[1].set_title('Heterogeneity PCA Space\n(each point = one PDAC tumor)')

    plt.suptitle('PCA of Intra-Tumor Heterogeneity Vectors', fontsize=12, fontweight='bold')
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '04_pca.png'))
    return pca, coords, H_scaled


def run_kmeans(H_scaled, coords, out_dir, k_range=(2, 6)):
    """K-means clustering on the standardised heterogeneity vectors.
    Tests k=2..6, picks the best k by silhouette score."""
    print('  K-means clustering...')
    sil_scores = {}
    for k in range(k_range[0], k_range[1]+1):
        km     = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = km.fit_predict(H_scaled)
        sil    = silhouette_score(H_scaled, labels)
        sil_scores[k] = sil
        print(f'    k={k}  silhouette={sil:.4f}')

    best_k = max(sil_scores, key=sil_scores.get)
    print(f'  Best k={best_k} (silhouette={sil_scores[best_k]:.4f})')

    km_best = KMeans(n_clusters=best_k, random_state=42, n_init=10)
    best_labels = km_best.fit_predict(H_scaled)

    pd.DataFrame({'sil_scores': sil_scores}).to_csv(
        os.path.join(out_dir, 'kmeans_silhouette.csv'))

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    axes[0].plot(list(sil_scores.keys()), list(sil_scores.values()),
                 'o-', color='steelblue', linewidth=2, markersize=7)
    axes[0].axvline(best_k, color='tomato', linestyle='--',
                    linewidth=1.5, label=f'Best k={best_k}')
    axes[0].set_xlabel('Number of clusters (k)')
    axes[0].set_ylabel('Silhouette score')
    axes[0].set_title('K-Means: Silhouette Scores')
    axes[0].legend(fontsize=9)
    axes[0].set_xticks(list(sil_scores.keys()))

    palette = plt.cm.tab10.colors
    for k_idx in range(best_k):
        mask = best_labels == k_idx
        axes[1].scatter(coords[mask, 0], coords[mask, 1],
                        alpha=0.55, s=20, color=palette[k_idx],
                        label=f'Cluster {k_idx+1} (n={mask.sum()})',
                        edgecolors='none')
    axes[1].set_xlabel(f'PC1')
    axes[1].set_ylabel(f'PC2')
    axes[1].set_title(f'K-Means Clusters (k={best_k}) in PCA Space')
    axes[1].legend(fontsize=8, markerscale=1.5)

    plt.suptitle(f'K-Means Heterogeneity Clustering (best k={best_k})',
                 fontsize=12, fontweight='bold')
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '05_kmeans.png'))
    return best_labels, best_k


def volume_correlation(magnitudes, volumes, out_dir):
    """Pearson + Spearman correlation between heterogeneity magnitude and tumor volume."""
    r_p, p_p = pearsonr(magnitudes,  volumes)
    r_s, p_s = spearmanr(magnitudes, volumes)
    print(f'  Pearson  r={r_p:.3f} p={p_p:.4f}')
    print(f'  Spearman r={r_s:.3f} p={p_s:.4f}')

    pd.DataFrame({
        'metric':   ['Pearson', 'Spearman'],
        'r':        [r_p, r_s],
        'p_value':  [p_p, p_s],
        'n_cases':  [len(magnitudes), len(magnitudes)],
    }).to_csv(os.path.join(out_dir, 'volume_correlation.csv'), index=False)

    vols_cm3 = volumes / 1000
    m, b     = np.polyfit(vols_cm3, magnitudes, 1)
    x_line   = np.linspace(vols_cm3.min(), vols_cm3.max(), 200)

    fig, ax = plt.subplots(figsize=(7, 6))
    ax.scatter(vols_cm3, magnitudes, alpha=0.45, s=18,
               color='steelblue', edgecolors='none')
    ax.plot(x_line, m*x_line+b, color='tomato', linewidth=2,
            label=f'Pearson r={r_p:.3f}, p={p_p:.3f}\n'
                  f'Spearman r={r_s:.3f}, p={p_s:.3f}')
    ax.set_xlabel('Tumor Volume (cm³)')
    ax.set_ylabel('Heterogeneity Magnitude (L2 norm)')
    ax.set_title('Intra-Tumor Heterogeneity vs. Tumor Size\n(PDAC cases)')
    ax.legend(fontsize=9)
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '06_volume_correlation.png'))


def plot_heatmap(central, peripheral, out_dir):
    """Mean central / peripheral / difference heatmap."""
    df_heat = pd.DataFrame({
        'Central':    central.mean(axis=0),
        'Peripheral': peripheral.mean(axis=0),
        'Difference': central.mean(axis=0) - peripheral.mean(axis=0),
    }, index=FEATURE_NAMES)

    fig, axes = plt.subplots(1, 3, figsize=(16, 10))
    for ax, col, title, cmap in zip(
        axes,
        ['Central', 'Peripheral', 'Difference'],
        ['Mean Central', 'Mean Peripheral', 'Difference (C−P)'],
        ['Blues', 'Oranges', 'coolwarm']
    ):
        sns.heatmap(df_heat[[col]], ax=ax, cmap=cmap,
                    center=0 if col=='Difference' else None,
                    yticklabels=FEATURE_NAMES, xticklabels=[col],
                    annot=True, fmt='.3f', annot_kws={'size': 7},
                    cbar_kws={'shrink': 0.6})
        ax.set_title(title, fontsize=11, fontweight='bold')
        ax.tick_params(axis='y', labelsize=7)

    plt.suptitle('Mean CoLIAGe Features: Central vs. Peripheral (PDAC cohort)',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    save_fig(fig, os.path.join(out_dir, 'plots', '07_heatmap.png'))

print('Analysis functions defined.')

"""# ── CELL 6: Run analysis for each fraction"""

# Stores summary stats across fractions for the cross-fraction comparison cell.
fraction_summaries = {}

for fraction in FRACTIONS:
    frac_str = f'fraction_{fraction}'
    out_dir  = os.path.join(OUTPUT_BASE_DIR, frac_str)
    os.makedirs(os.path.join(out_dir, 'plots'), exist_ok=True)

    print('\n' + '='*65)
    print(f'  ANALYSING: internal_fraction = {fraction}')
    print('='*65)

    # Load data
    central, peripheral, heterog, case_ids, oxi_volumes = load_fraction_data(fraction)
    n_cases = len(case_ids)
    print(f'  Cases: {n_cases}')

    # A1 — Paired tests
    print('\n── A1: Paired t-test + Wilcoxon ───────────────────────────────')
    df_tests = run_paired_tests(central, peripheral, out_dir)

    # A2 — Distributions
    print('\n── A2: Feature distributions ──────────────────────────────────')
    plot_distributions(central, peripheral, out_dir)

    # A3 — Magnitude
    print('\n── A3: Heterogeneity magnitude ─────────────────────────────────')
    magnitudes = analyse_magnitude(heterog, out_dir)

    # A4 — PCA
    print('\n── A4: PCA ─────────────────────────────────────────────────────')
    pca, coords, H_scaled = run_pca(heterog, out_dir)

    # A5 — K-means
    print('\n── A5: K-means clustering ──────────────────────────────────────')
    best_labels, best_k = run_kmeans(H_scaled, coords, out_dir)

    # A6 — Volume correlation (optional)
    if volumes is not None:
        print('\n── A6: Volume correlation ──────────────────────────────────────')
        volume_correlation(magnitudes, volumes, out_dir)
    else:
        print('\n── A6: Volume correlation — SKIPPED (no tumor_volumes.npy) ────')

    # A7 — Heatmap
    print('\n── A7: Feature heatmap ─────────────────────────────────────────')
    plot_heatmap(central, peripheral, out_dir)

    # Store summary for cross-fraction comparison
    fraction_summaries[fraction] = {
        'n_cases':      n_cases,
        'n_sig':        int(df_tests['sig_ttest'].sum()),
        'mean_mag':     float(magnitudes.mean()),
        'std_mag':      float(magnitudes.std(ddof=1)),
        'median_mag':   float(np.median(magnitudes)),
        'pca_pc1_var':  float(pca.explained_variance_ratio_[0]*100),
        'pca_pc12_var': float(np.cumsum(pca.explained_variance_ratio_)[1]*100),
        'best_k':       best_k,
        'sig_features': df_tests.loc[df_tests['sig_ttest'], 'feature'].tolist(),
    }

    print(f'\n  [{frac_str}] DONE — results saved to {out_dir}')

print('\n' + '='*65)
print('ALL FRACTIONS COMPLETE')
print('='*65)

"""# ── CELL 7: Cross-fraction comparison"""

# This is the key result: do heterogeneity patterns hold across all 3 fractions?
# If yes → heterogeneity is biological, not a mathematical artifact.
comp_dir = os.path.join(OUTPUT_BASE_DIR, 'comparison')
os.makedirs(os.path.join(comp_dir, 'plots'), exist_ok=True)
print('='*65)
print('CROSS-FRACTION COMPARISON')
print('='*65)

# Summary table
summary_rows = []
for frac, s in fraction_summaries.items():
    summary_rows.append({
        'fraction':      frac,
        'n_cases':       s['n_cases'],
        'n_sig_features':s['n_sig'],
        'mean_magnitude':round(s['mean_mag'], 4),
        'std_magnitude': round(s['std_mag'],  4),
        'median_magnitude': round(s['median_mag'], 4),
        'pca_pc1_var':   round(s['pca_pc1_var'],  1),
        'pca_pc12_var':  round(s['pca_pc12_var'], 1),
        'best_k':        s['best_k'],
    })
df_summary = pd.DataFrame(summary_rows)
df_summary.to_csv(os.path.join(comp_dir, 'fraction_comparison_summary.csv'), index=False)
print('\nSummary across fractions:')
print(df_summary.to_string(index=False))

# Significant features per fraction
print('\nSignificant features per fraction:')
all_sig = {}
for frac, s in fraction_summaries.items():
    sig = set(s['sig_features'])
    all_sig[frac] = sig
    print(f'  fraction={frac}: {len(sig)} features — {sorted(sig)}')

shared = all_sig[FRACTIONS[0]].intersection(*[all_sig[f] for f in FRACTIONS[1:]])
print(f'\nFeatures significant across ALL fractions ({len(shared)}):')
for f in sorted(shared):
    print(f'  {f}')

pd.DataFrame({'feature_significant_all_fractions': sorted(shared)}).to_csv(
    os.path.join(comp_dir, 'features_stable_across_fractions.csv'), index=False)

# ── Plot 1: Mean magnitude across fractions ───────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(15, 5))

fracs  = [s['fraction'] for s in summary_rows]
means  = [s['mean_magnitude'] for s in summary_rows]
stds   = [s['std_magnitude']  for s in summary_rows]
n_sigs = [s['n_sig_features'] for s in summary_rows]

axes[0].bar([str(f) for f in fracs], means, yerr=stds,
            color='mediumpurple', alpha=0.8, edgecolor='white',
            capsize=5)
axes[0].set_xlabel('Internal Fraction')
axes[0].set_ylabel('Mean Heterogeneity Magnitude')
axes[0].set_title('Magnitude Mean ± Std\nAcross Fractions')

axes[1].bar([str(f) for f in fracs], n_sigs,
            color='steelblue', alpha=0.8, edgecolor='white')
axes[1].set_xlabel('Internal Fraction')
axes[1].set_ylabel('Number of Significant Features')
axes[1].set_title('Significant Features (Bonferroni)\nAcross Fractions')
axes[1].set_ylim(0, 26)

pc12_vars = [s['pca_pc12_var'] for s in summary_rows]
axes[2].bar([str(f) for f in fracs], pc12_vars,
            color='tomato', alpha=0.8, edgecolor='white')
axes[2].set_xlabel('Internal Fraction')
axes[2].set_ylabel('Variance Explained (%)')
axes[2].set_title('PCA PC1+PC2 Variance Explained\nAcross Fractions')
axes[2].set_ylim(0, 100)

plt.suptitle('Cross-Fraction Stability of Heterogeneity Analysis',
             fontsize=13, fontweight='bold')
plt.tight_layout()
save_fig(fig, os.path.join(comp_dir, 'plots', 'cross_fraction_summary.png'))

# ── Plot 2: Significant features overlap across fractions (presence/absence heatmap)
all_features_union = sorted(
    all_sig[FRACTIONS[0]].union(*[all_sig[f] for f in FRACTIONS[1:]])
)
if all_features_union:
    presence = pd.DataFrame(
        {f: [1 if feat in all_sig[f] else 0 for feat in all_features_union]
         for f in FRACTIONS},
        index=all_features_union
    )
    fig, ax = plt.subplots(figsize=(8, max(4, len(all_features_union)*0.4)))
    sns.heatmap(presence, ax=ax, cmap='YlOrRd', vmin=0, vmax=1,
                linewidths=0.5, linecolor='white',
                annot=True, fmt='d', annot_kws={'size': 9},
                cbar_kws={'label': 'Significant (1=yes, 0=no)', 'shrink': 0.6})
    ax.set_xlabel('Internal Fraction', fontsize=11)
    ax.set_ylabel('Feature', fontsize=11)
    ax.set_title('Significant Features Across Fractions\n'
                 '(1 = Bonferroni p<0.05, 0 = not significant)',
                 fontsize=11, fontweight='bold')
    ax.tick_params(axis='y', labelsize=8)
    plt.tight_layout()
    save_fig(fig, os.path.join(comp_dir, 'plots', 'feature_stability_heatmap.png'))
else:
    print('No significant features found in any fraction — stability heatmap skipped.')

print(f'\nAll comparison results saved to: {comp_dir}')

"""# ── CELL 8: Final summary"""

print('HETEROGENEITY ANALYSIS COMPLETE')
print('='*65)
for s in summary_rows:
    print(f"  fraction={s['fraction']}: "
          f"{s['n_cases']} cases, "
          f"{s['n_sig_features']}/26 sig features, "
          f"mean_mag={s['mean_magnitude']:.4f}, "
          f"best_k={s['best_k']}")
print(f'  Features stable across ALL fractions: {len(shared)}')
print('='*65)
print(f'Outputs saved to: {OUTPUT_BASE_DIR}')

"""# plots all"""

import pandas as pd

csv_path = '/content/fraction_comparison_summary_ALL FRACTIONS.csv'
df = pd.read_csv(csv_path)

print("Contents of '/content/fraction_comparison_summary_ALL FRACTIONS.csv':")
print(df.head())

import pandas as pd
import matplotlib.pyplot as plt
import os

# Correctly load the CSV using semicolon as a separator
csv_path = '/content/fraction_comparison_summary_ALL FRACTIONS.csv'
df_summary = pd.read_csv(csv_path, sep=';')

# Define the output directory for plots if not already defined
# This assumes OUTPUT_BASE_DIR is defined in a prior cell, if not, use a default.
if 'OUTPUT_BASE_DIR' in locals():
    comp_dir = os.path.join(OUTPUT_BASE_DIR, 'comparison')
else:
    comp_dir = '/content/comparison_plots'
os.makedirs(os.path.join(comp_dir, 'plots'), exist_ok=True)

# Extract data from the DataFrame
fracs = df_summary['fraction'].astype(str).tolist()
means = df_summary['mean_magnitude'].tolist()
stds = df_summary['std_magnitude'].tolist()
n_sigs = df_summary['n_sig_features'].tolist()
pc12_vars = df_summary['pca_pc12_var'].tolist()

# Create the subplots
fig, axes = plt.subplots(1, 3, figsize=(18, 6)) # Increased figure size for better readability

# Plot 1: Mean magnitude across fractions
axes[0].bar(fracs, means, yerr=stds,
            color='mediumpurple', alpha=0.8, edgecolor='white',
            capsize=5)
axes[0].set_xlabel('Internal Fraction')
axes[0].set_ylabel('Mean Heterogeneity Magnitude')
axes[0].set_title('Magnitude Mean ± Std\nAcross Fractions')

# Plot 2: Number of Significant Features across fractions
axes[1].bar(fracs, n_sigs,
            color='steelblue', alpha=0.8, edgecolor='white')
axes[1].set_xlabel('Internal Fraction')
axes[1].set_ylabel('Number of Significant Features')
axes[1].set_title('Significant Features (Bonferroni)\nAcross Fractions')
axes[1].set_ylim(0, df_summary['n_sig_features'].max() * 1.2) # Adjust ylim dynamically

# Plot 3: PCA PC1+PC2 Variance Explained across fractions
axes[2].bar(fracs, pc12_vars,
            color='tomato', alpha=0.8, edgecolor='white')
axes[2].set_xlabel('Internal Fraction')
axes[2].set_ylabel('Variance Explained (%)')
axes[2].set_title('PCA PC1+PC2 Variance Explained\nAcross Fractions')
axes[2].set_ylim(0, 100)

plt.suptitle('Cross-Fraction Stability of Heterogeneity Analysis', fontsize=16, fontweight='bold')
plt.tight_layout(rect=[0, 0.03, 1, 0.95]) # Adjust layout to prevent suptitle overlap

# Save the figure
plot_path = os.path.join(comp_dir, 'plots', 'cross_fraction_summary_from_csv.png')
plt.savefig(plot_path, dpi=150, bbox_inches='tight')
plt.show()
print(f'Saved cross-fraction summary plot to: {plot_path}')

"""# wtf"""

"""
heatmap_significant_features.py
================================
Creates the "Significant Features Across Fractions" heatmap.

Requirements: numpy, pandas, matplotlib, seaborn, scipy

Run in Colab:
    !python heatmap_significant_features.py
Or paste directly into a Colab cell.
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os
from scipy.stats import ttest_rel

# ── CONFIG ────────────────────────────────────────────────────────────────────
# Base directory containing fraction subfolders
# Each subfolder must contain X_central.npy, X_peripheral.npy, case_ids.npy
AGGREGATED_BASE = "/content/drive/MyDrive/intra_tumor_heterogen_589/"
FRACTIONS       = [0.4, 0.5, 0.6]
SAVE_PATH       = "/content/drive/MyDrive/intra_tumor_heterogen_589/heatmap_sign_all_fractions.png"
# ─────────────────────────────────────────────────────────────────────────────

# ── Feature names ─────────────────────────────────────────────────────────────
HARALICK_BASE = [
    "AngularSecondMoment", "Contrast", "Correlation",
    "SumOfSquaresVariance", "SumAverage", "SumVariance", "SumEntropy",
    "Entropy", "DifferenceVariance", "DifferenceEntropy",
    "InfoMeasureCorr1", "InfoMeasureCorr2", "MaximalCorrelationCoeff",
]
FEATURE_NAMES = (
    [f"{f}_Primary"   for f in HARALICK_BASE] +
    [f"{f}_Secondary" for f in HARALICK_BASE]
)

# ── Run paired t-test per feature per fraction ────────────────────────────────
significance = {}   # fraction → array of 0/1 per feature

for fraction in FRACTIONS:
    frac_dir   = os.path.join(AGGREGATED_BASE, f"aggregated_{fraction}")
    central    = np.load(os.path.join(frac_dir, "central_vectors.npy"))
    peripheral = np.load(os.path.join(frac_dir, "peripheral_vectors.npy"))

    # Drop CT channel if present
    if central.shape[1] == 27:
        central    = central[:, 1:]
        peripheral = peripheral[:, 1:]

    assert central.shape[1] == 26

    n_feat = central.shape[1]
    sig    = np.zeros(n_feat, dtype=int)

    for i in range(n_feat):
        c = central[:, i];    p = peripheral[:, i]
        valid = np.isfinite(c) & np.isfinite(p)
        _, pv = ttest_rel(c[valid], p[valid])
        # Bonferroni correction
        if pv * n_feat < 0.05:
            sig[i] = 1

    significance[fraction] = sig
    n_sig = sig.sum()
    print(f"Fraction {fraction}: {n_sig}/26 significant features")

# ── Build DataFrame ───────────────────────────────────────────────────────────
df = pd.DataFrame(
    {fraction: significance[fraction] for fraction in FRACTIONS},
    index=FEATURE_NAMES
)

# 1. Υπολογισμός σκορ σταθερότητας
df["_stability"] = df.sum(axis=1)

# 2. Ταξινόμηση: Πρώτα κατά '_stability' (φθίνουσα) και μετά κατά το Index (αύξουσα)
df = df.sort_values(by="_stability", ascending=False).sort_index(kind="mergesort")

# 3. Αφαίρεση της βοηθητικής στήλης
df = df.drop(columns=["_stability"])



print(f"\nFeatures significant across ALL fractions: {(df.sum(axis=1)==3).sum()}")
print(f"Features significant across 2 fractions : {(df.sum(axis=1)==2).sum()}")
print(f"Features significant across 1 fraction  : {(df.sum(axis=1)==1).sum()}")
print(f"Features not significant in any          : {(df.sum(axis=1)==0).sum()}")

# ── Plot ──────────────────────────────────────────────────────────────────────
n_features = len(df)
fig_height = max(8, n_features * 0.42 + 2)

fig, ax = plt.subplots(figsize=(6, fig_height))

sns.heatmap(
    df,
    ax         = ax,
    cmap       = "YlOrRd",
    vmin       = 0,
    vmax       = 1,
    linewidths = 1.5,
    linecolor  = "white",
    annot      = True,
    fmt        = "d",
    annot_kws  = {"size": 11, "weight": "bold"},
    cbar_kws   = {"shrink": 0.6, "label": ""},
)

# Axis formatting
ax.set_xlabel("Internal Fraction", fontsize=12, labelpad=8)
ax.set_ylabel("Feature",          fontsize=12, labelpad=8)
ax.set_xticklabels([str(f) for f in FRACTIONS], fontsize=11)
ax.set_yticklabels(df.index, fontsize=9, rotation=0)
ax.tick_params(axis="x", which="both", bottom=False, top=False)
ax.tick_params(axis="y", which="both", left=False)

# Title
ax.set_title(
    "Significant Features Across Fractions\n"
    "(1 = Bonferroni p<0.05, 0 = not significant)",
    fontsize=13,
    fontweight="bold",
    pad=14,
)

plt.tight_layout()
os.makedirs(os.path.dirname(SAVE_PATH), exist_ok=True)
plt.savefig(SAVE_PATH, dpi=200, bbox_inches="tight", facecolor="white")
plt.show()
print(f"\nSaved: {SAVE_PATH}")