# -*- coding: utf-8 -*-
"""STEP2-DATA SPLITTING.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1im-F2L-9w62PFdW9W20n0ayJjFEgNoWJ

#STEP 2 — Stratified Train / Val / Test Split
"""

# @title
"""
Input  : master_X.npy, master_y.npy, master_ids.npy  (from Step 1)

Output : X_train/val/test.npy
         y_train/val/test.npy
         ids_train/val/test.npy
         scanner_train/val/test.npy  (if scanner labels provided)

Split ratio : 70 / 15 / 15  stratified by label.

CRITICAL: this split happens BEFORE EDA, ComBat, scaling, or
any feature selection. The test set is never touched again
until final evaluation.

CONFIGURE the paths and scanner info in the CONFIG block below.
"""

import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import glob
from google.colab import drive
import gdown

from google.colab import drive
drive.mount('/content/drive', force_remount=True)
output_drive_dir = '/content/drive/MyDrive'

# CONFIG
INPUT_DIR    = "/content/drive/MyDrive/classif_model_AYTO/step1_scenarioA/scenarioA"          # where master_X/y/ids.npy live
OUTPUT_DIR   = "/content/drive/MyDrive/classif_model_AYTO/step1_scenarioA"          # where split files will be saved
RANDOM_STATE = 42
VAL_RATIO    = 0.15               # fraction of total dataset
TEST_RATIO   = 0.15               # fraction of total dataset

# Scanner / site labels for ComBat harmonization (Step 3).
SCANNER_CSV = "/content/drive/MyDrive/metrics_batch1/scanner_labels_full.csv" # Set to None if you don't have scanner info yet.

# Example:  case_id,scanner
#           PDAC_001,Siemens
#           CTRL_001,GE

# ── Load master arrays ────────────────────────────────────────────────────────
X   = np.load(os.path.join(INPUT_DIR, "master_X_scenario_A.npy"))
y   = np.load(os.path.join(INPUT_DIR, "master_y_scenario_A.npy"))
ids = np.load(os.path.join(INPUT_DIR, "master_ids_scenario_A.npy"), allow_pickle=True)

print(f"Loaded master arrays: X={X.shape}, y={y.shape}, ids={ids.shape}")
print(f"Label distribution : PDAC={int((y==1).sum())}, "
      f"non-PDAC={int((y==0).sum())})")

# ── Optional: load scanner labels ────────────────────────────────────────────
if SCANNER_CSV is not None:
    scanner_df = pd.read_csv(SCANNER_CSV, sep=';')
    # Drop duplicates in 'case_id' before setting as index to avoid reindex error later
    scanner_df = scanner_df.drop_duplicates(subset=['case_id']).set_index("case_id")
    # Use reindex to align scanner_df with ids, filling NaN for missing IDs,
    # then convert to string 'nan' to avoid TypeError with np.unique
    scanners   = scanner_df.reindex(ids)['scanner'].fillna('nan').values
    print(f"\nScanner distribution: {dict(zip(*np.unique(scanners, return_counts=True)))}")
else:
    scanners = None
    print("No scanner labels provided — ComBat will be skipped in Step 3.")

"""# ── Split: Vendor-based (Siemens+Philips 70/15/15, Toshiba 30/70 calibration/external test)"""

# Step 1: carve out test (15%)
temp_ratio = VAL_RATIO + TEST_RATIO   # 0.30

X_train, X_temp, y_train, y_temp, ids_train, ids_temp = train_test_split(X, y, ids, test_size = temp_ratio, stratify = y, random_state = RANDOM_STATE)

# Step 2: split remainder into val / test (15% each)
X_val, X_test, y_val, y_test, ids_val, ids_test = train_test_split(X_temp, y_temp, ids_temp, test_size = 0.5, stratify = y_temp, random_state = RANDOM_STATE)

# ── Handle scanner labels if present ─────────────────────────────────────────
if scanners is not None:
    id_to_scanner = dict(zip(ids, scanners))
    sc_train = np.array([id_to_scanner[i] for i in ids_train])
    sc_val   = np.array([id_to_scanner[i] for i in ids_val])
    sc_test  = np.array([id_to_scanner[i] for i in ids_test])

# ── Verify split sizes and stratification ─────────────────────────────────────
total = len(y)
print(f"Split sizes:")
print(f"  Train : {len(y_train):4d} "
      f"({len(y_train)/total*100:.1f}%)  "
      f"PDAC={int((y_train==1).sum())}  "
      f"non-PDAC={int((y_train==0).sum())}")
print(f"  Val   : {len(y_val):4d} "
      f"({len(y_val)/total*100:.1f}%)  "
      f"PDAC={int((y_val==1).sum())}  "
      f"non-PDAC={int((y_val==0).sum())}")
print(f"  Test  : {len(y_test):4d} "
      f"({len(y_test)/total*100:.1f}%)  "
      f"PDAC={int((y_test==1).sum())}  "
      f"non-PDAC={int((y_test==0).sum())}")
assert len(y_train) + len(y_val) + len(y_test) == total, "Split sizes don't add up!"

"""# ── Save splits"""

splits = {
    "train": (X_train, y_train, ids_train),
    "val"  : (X_val,   y_val,   ids_val),
    "test" : (X_test,  y_test,  ids_test),
}

for name, (X_s, y_s, ids_s) in splits.items():
    np.save(os.path.join(OUTPUT_DIR, f"X_{name}_scenarioA.npy"),   X_s.astype(np.float32))
    np.save(os.path.join(OUTPUT_DIR, f"y_{name}_scenarioA.npy"),   y_s.astype(np.int32))
    np.save(os.path.join(OUTPUT_DIR, f"ids_{name}_scenarioA.npy"), ids_s.astype(str))

if scanners is not None:
    np.save(os.path.join(OUTPUT_DIR, "scanner_train_scenarioA.npy"), sc_train.astype(str))
    np.save(os.path.join(OUTPUT_DIR, "scanner_val_scenarioA.npy"),   sc_val.astype(str))
    np.save(os.path.join(OUTPUT_DIR, "scanner_test_scenarioA.npy"),  sc_test.astype(str))

print(f"Saved all split files to '{OUTPUT_DIR}/'")
print("Step 2 complete. Run step3_combat.py next.")

# Optional sanity check — run this after step2 completes
for split_name, ids_arr, y_arr, sc_arr in [
    ("train", ids_train, y_train, sc_train),
    ("val",   ids_val,   y_val,   sc_val),
    ("test",  ids_test,  y_test,  sc_test),
]:
    print(f"{split_name}:")
    for site in np.unique(sc_arr):
        idx  = sc_arr == site
        pdac = int(y_arr[idx].sum())
        ctrl = int((y_arr[idx] == 0).sum())
        print(f"  {site:<12} PDAC={pdac}  non-PDAC={ctrl}")