# -*- coding: utf-8 -*-
"""STEP 5b_RadiomicBranch_Classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDYxe8D9wUOQY4fRZf25_yzJpJl0paKd

# STEP 5b — Radiomic Classifier Training, Evaluation & Comparison

Input  : X_train/val/test_scaled.npy   (from step5_outputs)
         y_train/val/test.npy          (from step2_outputs)
         selected_feature_names.npy    (from step5_outputs)

Output (all saved to step5b_outputs):
  results_val.csv / results_test.csv   — per-model metrics table
  comparison_val.png / comparison_test.png — metric bar charts
  roc_curves_val.png / roc_curves_test.png — all ROC curves on one axes
  confusion_matrices.png               — 2×4 grid, val + test per model
  calibration_val.png / calibration_test.png — reliability diagrams
  best_model.pkl                       — best model by val AUC
  all_models.pkl                       — dict of all fitted models

Four classifiers trained with class-weight balancing:
  1. Logistic Regression  (L2, C=1.0)
  2. SVM                  (RBF kernel, probability=True for ROC)
  3. Random Forest        (500 trees)
  4. XGBoost              (scale_pos_weight for imbalance)

All hyperparameters are tuned on the VALIDATION set only via a small
grid search to prevent test-set leakage.  Final test metrics are
computed once, after the best hyperparameter per model is chosen.

Metrics reported
----------------
  ROC-AUC          — primary discrimination metric
  Average Precision — area under PR curve (better for imbalanced data)
  Brier Score       — calibration quality (lower = better)
  Accuracy
  Sensitivity       — recall for PDAC (class 1)
  Specificity       — recall for non-PDAC (class 0)
  F1-score          — harmonic mean of precision and recall
  MCC               — Matthews Correlation Coefficient (balanced)

# ── Imports
"""

import os, warnings
import numpy as np
import pandas as pd
import joblib
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

from sklearn.linear_model      import LogisticRegression
from sklearn.svm               import SVC
from sklearn.ensemble          import RandomForestClassifier
from sklearn.calibration       import CalibratedClassifierCV, calibration_curve
from sklearn.model_selection   import ParameterGrid
from sklearn.metrics           import (
    roc_auc_score, average_precision_score, brier_score_loss,
    accuracy_score, confusion_matrix, f1_score, matthews_corrcoef,
    roc_curve, precision_recall_curve,
)
from sklearn.preprocessing     import label_binarize
from xgboost                   import XGBClassifier

warnings.filterwarnings("ignore")

# ── Google Colab / Drive ──────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive', force_remount=True)

STEP2_DIR   = "/content/drive/MyDrive/classif_model_AYTO/steps_scenarioA/step2_scenarioA"
STEP5_DIR   = "/content/drive/MyDrive/classif_model_AYTO/steps_scenarioA/step5_scenarioA"
OUTPUT_DIR  = "/content/drive/MyDrive/classif_model_AYTO/steps_scenarioA/step5_B_scenarioA"
os.makedirs(OUTPUT_DIR, exist_ok=True)

RANDOM_STATE = 42
DPI          = 150

# Colour palette — one per model
PALETTE = {
    "LogReg" : "#2196F3",   # blue
    "SVM"    : "#FF9800",   # orange
    "RF"     : "#4CAF50",   # green
    "XGB"    : "#E91E63",   # pink
}

"""# ── Load data"""

X_train = np.load(os.path.join(STEP5_DIR, "X_train_scaled_scenarioA.npy"))
X_val   = np.load(os.path.join(STEP5_DIR, "X_val_scaled_scenarioA.npy"))
X_test  = np.load(os.path.join(STEP5_DIR, "X_test_scaled_scenarioA.npy"))

y_train = np.load(os.path.join(STEP2_DIR, "y_train_scenarioA.npy"))
y_val   = np.load(os.path.join(STEP2_DIR, "y_val_scenarioA.npy"))
y_test  = np.load(os.path.join(STEP2_DIR, "y_test_scenarioA.npy"))

feat_names = np.load(os.path.join(STEP5_DIR, "selected_feature_names_scenarioA.npy"), allow_pickle=True).tolist()

n_pos  = int(y_train.sum())
n_neg  = int((1 - y_train).sum())
spw    = n_neg / n_pos          # scale_pos_weight for XGBoost

print(f"Loaded  train={X_train.shape}  val={X_val.shape}  test={X_test.shape}")
print(f"PDAC: train={n_pos}  val={int(y_val.sum())}  test={int(y_test.sum())}")
print(f"Features: {feat_names}\n")

X_train[0,:]

"""## Add this right after loading data in step5b"""

# Add this right after loading data in step5b
print("Label distribution check:")
print(f"  Train  — PDAC={y_train.sum():.0f}  non-PDAC={(1-y_train).sum():.0f}")
print(f"  Val    — PDAC={y_val.sum():.0f}    non-PDAC={(1-y_val).sum():.0f}")
print(f"  Test   — PDAC={y_test.sum():.0f}   non-PDAC={(1-y_test).sum():.0f}")

# And check a few feature values look sensible
import pandas as pd
pd.DataFrame(X_train, columns=feat_names).describe().to_csv("feature_check_scenarioA.csv")

"""# Helper: compute all metrics from true labels + predicted probabilities"""

def compute_metrics(y_true: np.ndarray, y_prob: np.ndarray,
                    threshold: float = 0.5) -> dict:
    y_pred = (y_prob >= threshold).astype(int)
    tn, fp, fn, tp = confusion_matrix(y_true, y_pred, labels=[0, 1]).ravel()

    sensitivity = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    specificity = tn / (tn + fp) if (tn + fp) > 0 else 0.0

    return {
        "ROC-AUC"  : round(roc_auc_score(y_true, y_prob), 4),
        "Avg-Prec" : round(average_precision_score(y_true, y_prob), 4),
        "Brier"    : round(brier_score_loss(y_true, y_prob), 4),
        "Accuracy" : round(accuracy_score(y_true, y_pred), 4),
        "Sensitivity": round(sensitivity, 4),
        "Specificity": round(specificity, 4),
        "F1"       : round(f1_score(y_true, y_pred, zero_division=0), 4),
        "MCC"      : round(matthews_corrcoef(y_true, y_pred), 4),
        "TP": tp, "TN": tn, "FP": fp, "FN": fn,
        "threshold": threshold,
    }

def find_best_threshold(y_true: np.ndarray, y_prob: np.ndarray) -> float:
    """Youden's J: maximises sensitivity + specificity - 1 on the given split."""
    fpr, tpr, thresholds = roc_curve(y_true, y_prob)
    j_scores = tpr - fpr
    best_idx = np.argmax(j_scores)
    return float(thresholds[best_idx])

"""# Model definitions with small validation-set hyperparameter grids"""

MODEL_GRIDS = {
    "LogReg": {
        "class": LogisticRegression,
        "fixed": {"solver": "lbfgs", "max_iter": 1000,
                  "class_weight": "balanced", "random_state": RANDOM_STATE},
        "grid" : {"C": [0.01, 0.1, 1.0, 10.0]},
    },
    "SVM": {
        "class": SVC,
        "fixed": {"kernel": "rbf", "probability": True,
                  "class_weight": "balanced", "random_state": RANDOM_STATE},
        "grid" : {"C": [0.1, 1.0, 10.0], "gamma": ["scale", "auto"]},
    },
    "RF": {
        "class": RandomForestClassifier,
        "fixed": {"n_estimators": 500, "class_weight": "balanced_subsample",
                  "random_state": RANDOM_STATE, "n_jobs": -1},
        "grid" : {"max_depth": [None, 5, 10],
                  "min_samples_leaf": [1, 2, 4]},
    },
    "XGB": {
        "class": XGBClassifier,
        "fixed": {"n_estimators": 300, "eval_metric": "logloss",
                  "scale_pos_weight": spw,
                  "random_state": RANDOM_STATE, "verbosity": 0, "n_jobs": -1},
        "grid" : {"max_depth": [3, 5, 7],
                  "learning_rate": [0.01, 0.05, 0.1],
                  "subsample": [0.8, 1.0]},
    },
}

"""# Training loop — grid search on val AUC, never touching test"""

best_models   = {}    # name → fitted model
best_hparams  = {}    # name → best param dict
val_probs     = {}    # name → y_prob on val
test_probs    = {}    # name → y_prob on test
best_thresholds = {}  # name → Youden threshold from val

for name, cfg in MODEL_GRIDS.items():
    print(f"─ {name} ──────────────────────────────────────")
    best_auc   = -1
    best_model = None
    best_param = None

    for params in ParameterGrid(cfg["grid"]):
        merged = {**cfg["fixed"], **params}
        clf    = cfg["class"](**merged)
        clf.fit(X_train, y_train)
        prob_v = clf.predict_proba(X_val)[:, 1]
        auc_v  = roc_auc_score(y_val, prob_v)

        if auc_v > best_auc:
            best_auc   = auc_v
            best_model = clf
            best_param = params

    print(f"  Best params : {best_param}")
    print(f"  Val AUC     : {best_auc:.4f}")

    best_models[name]     = best_model
    best_hparams[name]    = best_param
    val_probs[name]       = best_model.predict_proba(X_val)[:, 1]
    test_probs[name]      = best_model.predict_proba(X_test)[:, 1]
    best_thresholds[name] = find_best_threshold(y_val, val_probs[name])

print()

"""# Compute metrics for val and test using the Youden threshold from val"""

records_val  = []
records_test = []

for name in best_models:
    thr = best_thresholds[name]
    mv  = compute_metrics(y_val,  val_probs[name],  threshold=thr)
    mt  = compute_metrics(y_test, test_probs[name], threshold=thr)
    records_val.append( {"Model": name, **mv})
    records_test.append({"Model": name, **mt})

df_val  = pd.DataFrame(records_val).set_index("Model")
df_test = pd.DataFrame(records_test).set_index("Model")

# Identify best model by val AUC
best_model_name = df_val["ROC-AUC"].idxmax()

print("=" * 30)
print("VALIDATION METRICS")
print("=" * 30)
print(df_val[["ROC-AUC","Avg-Prec","Brier","Accuracy",
              "Sensitivity","Specificity","F1","MCC"]].to_string())
print(f"Best model by val AUC: {best_model_name}\n")

print("TEST METRICS")
print(df_test[["ROC-AUC","Avg-Prec","Brier","Accuracy",
               "Sensitivity","Specificity","F1","MCC"]].to_string())

df_val.to_csv( os.path.join(OUTPUT_DIR, "results_val_scenarioA.csv"))
df_test.to_csv(os.path.join(OUTPUT_DIR, "results_test_scenarioA.csv"))

"""# Plot 1 — ROC curves (val and test side-by-side)"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(
    axes,
    [(val_probs, y_val, "Validation"), (test_probs, y_test, "Test")]
):
    for name, prob in probs.items():
        fpr, tpr, _ = roc_curve(y_true, prob)
        auc = roc_auc_score(y_true, prob)
        ax.plot(fpr, tpr, label=f"{name}  AUC={auc:.3f}",
                color=PALETTE[name], lw=2)
    ax.plot([0, 1], [0, 1], "k--", lw=1)
    ax.set_xlabel("False Positive Rate", fontsize=11)
    ax.set_ylabel("True Positive Rate", fontsize=11)
    ax.set_title(f"ROC Curves — {title}", fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "roc_curves_scenarioA.png"), dpi=DPI)
plt.close()
print("Saved: roc_curves_scenarioA.png")

"""# Plot 2 — Metric comparison bar charts (val and test)"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import os
import numpy as np
import torch
import matplotlib
#matplotlib.use('QtAgg')  # Or use 'QtAgg' if you have PyQt installed
import matplotlib.pyplot as plt

# @title
METRIC_COLS = ["ROC-AUC", "Avg-Prec", "Accuracy", "Sensitivity",
               "Specificity", "F1", "MCC"]

for df, split in [(df_val, "val"), (df_test, "test")]:
    fig, axes = plt.subplots(1, len(METRIC_COLS), figsize=(18, 4))
    for ax, metric in zip(axes, METRIC_COLS):
        vals   = df[metric]
        colors = [PALETTE[m] for m in vals.index]
        bars   = ax.bar(vals.index, vals.values, color=colors, edgecolor="white",
                        linewidth=0.8)
        ax.set_title(metric, fontsize=10, fontweight="bold")
        ax.set_ylim(0, 1.08)
        ax.set_xticklabels(vals.index, fontsize=10, rotation=20)
        ax.grid(axis="y", alpha=0.3)
        for bar, v in zip(bars, vals.values):
            ax.text(bar.get_x() + bar.get_width() / 2, v + 0.01,
                    f"{v:.3f}", ha="center", va="bottom", fontsize=10)
        # special axis for Brier (lower = better)
    # Brier separately
    fig2, ax2 = plt.subplots(figsize=(4, 4))
    brier_vals = df["Brier"]
    bars2 = ax2.bar(brier_vals.index, brier_vals.values,
                    color=[PALETTE[m] for m in brier_vals.index],
                    edgecolor="white")
    ax2.set_title("Brier Score (↓ better)", fontsize=10, fontweight="bold")
    ax2.set_ylim(0, max(brier_vals.values) * 1.3 + 0.05)
    ax2.grid(axis="y", alpha=0.3)
    for bar, v in zip(bars2, brier_vals.values):
        ax2.text(bar.get_x() + bar.get_width() / 2, v + 0.002,
                 f"{v:.3f}", ha="center", va="bottom", fontsize=9)
    fig2.tight_layout()
    fig2.savefig(os.path.join(OUTPUT_DIR, f"brier_{split}.png"), dpi=DPI)
    plt.close(fig2)

    fig.suptitle(f"Classifier Comparison — {split.capitalize()} Set",
                 fontsize=13, fontweight="bold", y=1.02)
    fig.tight_layout()
    plt.show()
    fig.savefig(os.path.join(OUTPUT_DIR, f"comparison_{split}_scenarioA.png"),
                dpi=DPI, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved: comparison_{split}.png  brier_{split}_scenarioA.png")

import os
import matplotlib.pyplot as plt

METRIC_COLS = ["ROC-AUC", "Avg-Prec", "Accuracy", "Sensitivity", "Specificity", "F1", "MCC"]

for df, split in [(df_val, "val"), (df_test, "test")]:
    # 1. Δημιουργία πλέγματος 4 σειρών και 3 στηλών με κατάλληλο μέγεθος για σελίδα διατριβής
    fig, axes = plt.subplots(3, 4, figsize=(14, 16))
    axes_flat = axes.flatten()  # Μετατροπή σε 1D array (0 έως 11) για εύκολο indexing

    # ─── Α. ΣΧΕΔΙΑΣΗ ΤΩΝ 7 ΒΑΣΙΚΩΝ ΜΕΤΡΙΚΩΝ ───
    for idx, metric in enumerate(METRIC_COLS):
        ax = axes_flat[idx]
        vals = df[metric]
        colors = [PALETTE[m] for m in vals.index]

        # Αυξάνουμε το πάχος των μπαρών (height/width) και προσθέτουμε edgecolor
        bars = ax.bar(vals.index, vals.values, color=colors, edgecolor="white", linewidth=1.0, width=0.6)

        # Μεγαλύτερες γραμματοσειρές για τίτλους και άξονες
        ax.set_title(metric, fontsize=12, fontweight="bold", pad=8)
        ax.set_ylim(0, 1.12)  # Δίνουμε λίγο χώρο για τα text labels
        ax.set_xticklabels(vals.index, fontsize=11, rotation=15)
        ax.tick_params(axis="y", labelsize=10)
        ax.grid(axis="y", alpha=0.3, linestyle="--")

        # Προσθήκη τιμών πάνω από τις μπάρες με μεγαλύτερο font
        for bar, v in zip(bars, vals.values):
            ax.text(bar.get_x() + bar.get_width() / 2, v + 0.015,
                    f"{v:.3f}", ha="center", va="bottom", fontsize=11, fontweight="medium")

    # ─── Β. ΣΧΕΔΙΑΣΗ ΤΟΥ BRIER SCORE ΣΤΟ 8ο SUBPLOT (Index 7) ───
    ax_brier = axes_flat[7]
    brier_vals = df["Brier"]
    colors_brier = [PALETTE[m] for m in brier_vals.index]

    bars_brier = ax_brier.bar(brier_vals.index, brier_vals.values, color=colors_brier, edgecolor="white", linewidth=1.0, width=0.6)

    ax_brier.set_title("Brier Score (↓ better)", fontsize=12, fontweight="bold", pad=8)
    ax_brier.set_ylim(0, max(brier_vals.values) * 1.25 + 0.05)
    ax_brier.set_xticklabels(brier_vals.index, fontsize=11, rotation=15)
    ax_brier.tick_params(axis="y", labelsize=10)
    ax_brier.grid(axis="y", alpha=0.3, linestyle="--")

    for bar, v in zip(bars_brier, brier_vals.values):
        ax_brier.text(bar.get_x() + bar.get_width() / 2, v + 0.005,
                     f"{v:.3f}", ha="center", va="bottom", fontsize=10, fontweight="medium")

    # ─── Γ. ΑΠΕΝΕΡΓΟΠΟΙΗΣΗ ΤΩΝ ΥΠΟΛΟΙΠΩΝ 4 ΑΔΕΙΩΝ SUBPLOTS (Indices 8, 9, 10, 11) ───
    for idx in range(8, 12):
        axes_flat[idx].axis('off')

    # ─── Δ. ΓΕΝΙΚΟΣ ΤΙΤΛΟΣ ΚΑΙ ΕΞΑΓΩΓΗ ΕΙΚΟΝΑΣ ───
    fig.suptitle(f"Classifier Comparison — {split.capitalize()} Set",
                 fontsize=16, fontweight="bold", y=0.98)

    # Το tight_layout() φροντίζει να μην κλείνουν οι ετικέτες μεταξύ των σειρών
    fig.tight_layout()
    plt.show()

    # Αποθήκευση σε υψηλή ανάλυση (300 DPI) για το PDF της διατριβής
    output_path = os.path.join(OUTPUT_DIR, f"comparison_{split}_grid4x3.png")
    fig.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)

    print(f"Saved complete 4x2 grid plot for {split} set to: {output_path}")

"""# Plot 3 — Confusion matrices (2 rows × 4 cols: top=val, bottom=test)"""

model_names = list(best_models.keys())
fig, axes   = plt.subplots(2, 4, figsize=(16, 7))

for col, name in enumerate(model_names):
    for row, (probs, y_true, split) in enumerate(
        [(val_probs, y_val, "Val"), (test_probs, y_test, "Test")]
    ):
        thr  = best_thresholds[name]
        pred = (probs[name] >= thr).astype(int)
        cm   = confusion_matrix(y_true, pred, labels=[0, 1])
        ax   = axes[row][col]

        im = ax.imshow(cm, cmap="Blues", aspect="auto")
        for i in range(2):
            for j in range(2):
                ax.text(j, i, str(cm[i, j]), ha="center", va="center",
                        fontsize=14, fontweight="bold",
                        color="white" if cm[i, j] > cm.max() / 2 else "black")

        ax.set_xticks([0, 1]); ax.set_xticklabels(["non-PDAC", "PDAC"])
        ax.set_yticks([0, 1]); ax.set_yticklabels(["non-PDAC", "PDAC"])
        ax.set_xlabel("Predicted", fontsize=9)
        ax.set_ylabel("Actual", fontsize=9)
        ax.set_title(f"{name} — {split}", fontsize=10, fontweight="bold",
                     color=PALETTE[name])

fig.suptitle("Confusion Matrices  (top: Validation | bottom: Test)",
             fontsize=13, fontweight="bold")
plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrices_scenarioA.png"), dpi=DPI, bbox_inches="tight")
plt.close()
print("Saved: confusion_matrices_scenarioA.png")

"""# Plot 4 — Calibration / reliability diagrams"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(
    axes,
    [(val_probs, y_val, "Validation"), (test_probs, y_test, "Test")]
):
    ax.plot([0, 1], [0, 1], "k--", lw=1, label="Perfect calibration")
    for name, prob in probs.items():
        frac_pos, mean_pred = calibration_curve(y_true, prob, n_bins=8,
                                                strategy="uniform")
        brier = brier_score_loss(y_true, prob)
        ax.plot(mean_pred, frac_pos, "o-", color=PALETTE[name], lw=2,
                label=f"{name}  Brier={brier:.3f}")
    ax.set_xlabel("Mean predicted probability", fontsize=11)
    ax.set_ylabel("Fraction of positives (PDAC)", fontsize=11)
    ax.set_title(f"Calibration — {title}", fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "calibration_scenarioA.png"), dpi=DPI)
plt.close()
print("Saved: calibration_scenarioA.png")

"""# Plot 5 — Precision-Recall curves"""

fig, axes = plt.subplots(1, 2, figsize=(12, 5))
for ax, (probs, y_true, title) in zip(
    axes,
    [(val_probs, y_val, "Validation"), (test_probs, y_test, "Test")]
):
    baseline = y_true.mean()
    ax.axhline(baseline, color="gray", linestyle="--", lw=1,
               label=f"Baseline (prevalence={baseline:.2f})")
    for name, prob in probs.items():
        prec, rec, _ = precision_recall_curve(y_true, prob)
        ap = average_precision_score(y_true, prob)
        ax.plot(rec, prec, color=PALETTE[name], lw=2,
                label=f"{name}  AP={ap:.3f}")
    ax.set_xlabel("Recall (Sensitivity)", fontsize=11)
    ax.set_ylabel("Precision", fontsize=11)
    ax.set_title(f"Precision-Recall — {title}", fontsize=12, fontweight="bold")
    ax.legend(fontsize=9)
    ax.grid(alpha=0.3)

plt.tight_layout()
plt.show()

plt.savefig(os.path.join(OUTPUT_DIR, "pr_curves_scenarioA.png"), dpi=DPI)
plt.close()
print("Saved: pr_curves_scenarioA.png")

"""# Save models"""

joblib.dump(best_models[best_model_name], os.path.join(OUTPUT_DIR, "best_model_scenarioA.pkl"))
joblib.dump(best_models, os.path.join(OUTPUT_DIR, "all_models_scenarioA.pkl"))
joblib.dump(best_hparams, os.path.join(OUTPUT_DIR, "best_hparams_scenarioA.pkl"))

"""# Final printed comparison"""

print(f"{'Model':<10} {'Val AUC':>8} {'Test AUC':>9} {'Val Sens':>9} "
      f"{'Test Sens':>10} {'Val Spec':>9} {'Test Spec':>10} {'Val F1':>8} {'Test F1':>8}")
print("-" * 85)
for name in model_names:
    v = df_val.loc[name]
    t = df_test.loc[name]
    star = " ★" if name == best_model_name else ""
    print(f"{name:<10} {v['ROC-AUC']:>8.4f} {t['ROC-AUC']:>9.4f} "
          f"{v['Sensitivity']:>9.4f} {t['Sensitivity']:>10.4f} "
          f"{v['Specificity']:>9.4f} {t['Specificity']:>10.4f} "
          f"{v['F1']:>8.4f} {t['F1']:>8.4f}{star}")

print(f"Best model: {best_model_name}"
      f"(val AUC={df_val.loc[best_model_name,'ROC-AUC']:.4f}, "
      f"test AUC={df_test.loc[best_model_name,'ROC-AUC']:.4f})")
print(f"\nAll outputs saved to: {OUTPUT_DIR}")
print("Run step6_cnn_patch_training.py next.")