# -*- coding: utf-8 -*-
"""STEP3_COMBAT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v6LrMWnd8lgzc3B2-eDLxmIDl6xtv3ow

STEP 3 — Partial ComBat Harmonization (neuroHarmonize)
=======================================================
"""

# @title
"""
**Input (from Step 2)**:
* X_train/val/test.npy - feature arrays
* y_train/val/test.npy - labels
* scanner_train/val/test.npy - scanner labels

**Output** :
* X_train/val/test_harmonized.npy
* combat_model.pkl

**PARTIAL COMBAT LOGIC:**
  - ComBat is fit on training cases from COMBAT_SITES only
    (Siemens, Toshiba, Philips → ~253 cases)
  - ComBat estimates are then applied to val and test cases
    from those same sites
  - Cases from EXCLUDE_SITES (GE, Canon) and unknown scanner
    cases pass through with features unchanged
  - NO CASES ARE DROPPED — all 500 participate in downstream steps
  - harmonizationLearn is fit on TRAINING data only
  - harmonizationApply is used on val/test — no re-fitting

**CRITICAL:** Split must happen before ComBat (Step 2 before Step 3).
Fitting ComBat on all 500 cases before splitting would leak test
scanner statistics into training, violating evaluation integrity.

"""

!pip install neuroHarmonize

import os
import pickle
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

# ── CONFIG ───────────────────────────────────────────────────────────────────
output_drive_dir = '/content/drive/MyDrive'

# CONFIG
INPUT_DIR  = "/content/drive/MyDrive/classif_model_AYTO/steps_scenarioA/step2_scenarioA"
OUTPUT_DIR = "/content/drive/MyDrive/classif_model_AYTO/steps_scenarioA/step3_scenarioA"
#os.makedirs(OUTPUT_DIR, exist_ok=True)

COMBAT_SITES = {"SIEMENS", "TOSHIBA", "Philips", "GE MEDICAL SYSTEMS"} # Scanners included in ComBat harmonization.
# Must have: (a) enough cases per scanner, (b) both classes represented.

# Scanners excluded from ComBat — too few cases for reliable estimation. These cases pass through with features unchanged.
# Unknown scanner cases (labelled "UNKNOWN" or "NA") are also excluded automatically because they are not in COMBAT_SITES.
EXCLUDE_SITES = {"Canon Medical Systems", "UNKNOWN", "NA", "nan"} # OLA TA PDAC CASES / SCENARIO A & B

MIN_CASES_PER_SITE = 15 # Minimum cases per scanner in the training split to proceed with ComBat. If any COMBAT_SITE falls below this, a warning is printed.
UNKNOWN_LABEL = "NA" # Label for unknown/missing scanner entries in scanner_*.npy

# Check whether scanner labels exist
scanner_train_path = os.path.join(INPUT_DIR, "scanner_train_scenarioA.npy")

if not os.path.exists(scanner_train_path):
    print("No scanner_train.npy found — ComBat skipped.")
    print("Copying raw split arrays through as harmonized outputs.\n")
    for split in ["train", "val", "test"]:
        X = np.load(os.path.join(INPUT_DIR, f"X_{split}_scenarioA.npy"))
        np.save(os.path.join(OUTPUT_DIR, f"X_{split}_harmonized_scenarioA.npy"), X)
        print(f"  Copied X_{split}.npy → X_{split}_harmonized_scenarioA.npy  {X.shape}")
    print("\nStep 3 complete (no harmonization). Run step4_eda.py next.")
    exit(0)

"""# Load all splits"""

!pip install neuroCombat

# Load all splits
try:
    from neuroHarmonize import harmonizationLearn, harmonizationApply
except ImportError:
    raise ImportError(
        "neuroHarmonize not installed. Run: pip install neuroHarmonize\n"
        "Or remove scanner_train.npy to skip harmonization."
    )

# Loaded master arrays: X=(500, 104) FEATURE MATRIX,
X_train = np.load(os.path.join(INPUT_DIR, "X_train_scenarioA.npy"))
X_val   = np.load(os.path.join(INPUT_DIR, "X_val_scenarioA.npy"))
X_test  = np.load(os.path.join(INPUT_DIR, "X_test_scenarioA.npy"))

#  y=(500,) LABEL COUNTS (0: 250, 1: 250)
y_train = np.load(os.path.join(INPUT_DIR, "y_train_scenarioA.npy"))
y_val   = np.load(os.path.join(INPUT_DIR, "y_val_scenarioA.npy"))
y_test  = np.load(os.path.join(INPUT_DIR, "y_test_scenarioA.npy"))

# scanner distribution per data split
sc_train = np.load(os.path.join(INPUT_DIR, "scanner_train_scenarioA.npy"), allow_pickle=True).astype(str)
sc_val   = np.load(os.path.join(INPUT_DIR, "scanner_val_scenarioA.npy"),   allow_pickle=True).astype(str)
sc_test  = np.load(os.path.join(INPUT_DIR, "scanner_test_scenarioA.npy"),  allow_pickle=True).astype(str)

# Normalise unknown labels
for arr in [sc_train, sc_val, sc_test]:
    arr[np.isin(arr, list(EXCLUDE_SITES))] = UNKNOWN_LABEL

print("STEP 3 — Partial ComBat Harmonization (Scenario A)")
print(f"\nDataset splits:")
print(f"  Train : {len(y_train)} cases")
print(f"  Val   : {len(y_val)} cases")
print(f"  Test  : {len(y_test)} cases")

print("FENIA'S CHECK")
print(f"\n X splits:")
print(f"  Train : {len(X_train)} cases")
print(f"  Val   : {len(X_val)} cases")
print(f"  Test  : {len(X_test)} cases")

print(f"\n SCANNERS splits:")
print(f"  Train : {len(sc_train)} cases")
print(f"  Val   : {len(sc_val)} cases")
print(f"  Test  : {len(sc_test)} cases")

sc_train.shape

sc_val.shape

sc_test.shape

"""# Report scanner distribution across all splits"""

print("Scanner distribution:")
print(f"  {'Scanner':<12} {'Train':>6} {'Val':>6} {'Test':>6} {'Total':>6}  ComBat?")
print(f"  {'-'*12} {'-'*6} {'-'*6} {'-'*6} {'-'*6}  {'-'*7}")

all_scanners = np.unique(np.concatenate([sc_train, sc_val, sc_test]))
for site in sorted(all_scanners):
    n_tr = int((sc_train == site).sum())
    n_va = int((sc_val   == site).sum())
    n_te = int((sc_test  == site).sum())
    flag = "YES" if site in COMBAT_SITES else "passthrough"
    print(f"  {site:<12} {n_tr:>6} {n_va:>6} {n_te:>6} {n_tr+n_va+n_te:>6}  {flag}")

    # In step3, after loading scanner arrays, standardize nan strings:
    for arr in [sc_train, sc_val, sc_test]:
      arr[arr == "nan"] = "UNKNOWN"
      arr[arr == "NA"]  = "UNKNOWN"
      arr[arr == ""]    = "UNKNOWN"

print(f"\nCombat sites    : {sorted(COMBAT_SITES)}")
print(f"Passthrough sites: all others (features unchanged)")

"""# Warn if any ComBat site has too few training cases or class imbalance"""

print("Per-site training class distribution:")
for site in sorted(COMBAT_SITES):
    idx    = sc_train == site
    n      = idx.sum()
    n_pdac = int(y_train[idx].sum())
    n_ctrl = int((y_train[idx] == 0).sum())
    ratio  = n_pdac / n if n > 0 else 0

    warn = ""
    if n < MIN_CASES_PER_SITE:
        warn = "  ← WARNING: too few cases"
    elif ratio > 0.75:
        warn = "  ← CAUTION: PDAC-heavy (class imbalance)"
    elif ratio < 0.25:
        warn = "  ← CAUTION: non-PDAC-heavy (class imbalance)"

    print(f"  {site:<12}  n={n:>3}  PDAC={n_pdac:>3}  non-PDAC={n_ctrl:>3}  "
          f"PDAC%={ratio*100:.0f}%{warn}")

"""# (Partial) ComBat FUNCTIONS"""

def get_combat_mask(scanners: np.ndarray) -> np.ndarray:
    """
    Returns a boolean mask: True for cases that belong to COMBAT_SITES.
    Cases from excluded or unknown sites are False → passthrough.
    """
    return np.array([s in COMBAT_SITES for s in scanners])

def reconstruct_full_array(X_original: np.ndarray,
                            X_harmonized_subset: np.ndarray,
                            combat_mask: np.ndarray) -> np.ndarray:
    """
    Slot the harmonized subset back into a copy of the original array,
    preserving original values for passthrough cases.

    Parameters
    ----------
    X_original         : (N, F)  full array (all cases)
    X_harmonized_subset: (M, F)  ComBat output (M = combat_mask.sum())
    combat_mask        : (N,)    boolean, True where ComBat was applied

    Returns
    -------
    (N, F) array — ComBat cases replaced, passthrough cases unchanged
    """
    X_out = X_original.copy()
    X_out[combat_mask] = X_harmonized_subset
    return X_out

"""# Build masks"""

mask_tr = get_combat_mask(sc_train)
mask_va = get_combat_mask(sc_val)
mask_te = get_combat_mask(sc_test)

print(f"Cases entering ComBat:")
print(f"  Train : {mask_tr.sum():>3} / {len(mask_tr)} "
      f"({mask_tr.sum()/len(mask_tr)*100:.1f}%)")
print(f"  Val   : {mask_va.sum():>3} / {len(mask_va)} "
      f"({mask_va.sum()/len(mask_va)*100:.1f}%)")
print(f"  Test  : {mask_te.sum():>3} / {len(mask_te)} "
      f"({mask_te.sum()/len(mask_te)*100:.1f}%)")

print(f"\nPassthrough (features unchanged):")
print(f"  Train : {(~mask_tr).sum():>3}")
print(f"  Val   : {(~mask_va).sum():>3}")
print(f"  Test  : {(~mask_te).sum():>3}")

if mask_tr.sum() == 0:
    print("\nERROR: No training cases qualify for ComBat.")
    print("Check that COMBAT_SITES match your scanner label strings exactly.")
    exit(1)

"""# Fit ComBat on training cases from COMBAT_SITES only"""

X_tr_cb  = X_train[mask_tr]        # (M_train, F)  ComBat-eligible training cases
sc_tr_cb = sc_train[mask_tr]       # (M_train,)    their scanner labels
y_tr_cb  = y_train[mask_tr]        # (M_train,)    their class labels

# neuroHarmonize covariates DataFrame:
covars_train = pd.DataFrame({
    "SITE": sc_tr_cb, # batch variable (scanner) — this effect is removed
    "PDAC": y_tr_cb.astype(int), # protected covariate — this effect is PRESERVED
})

print(f"Fitting ComBat on {len(X_tr_cb)} training cases "
      f"from {sorted(np.unique(sc_tr_cb))} ...")

combat_model, X_tr_cb_h = harmonizationLearn(
    data   = X_tr_cb.copy().astype(np.float64),
    covars = covars_train,
    eb     = True,       # empirical Bayes (recommended)
)

print(f"ComBat fit complete.")
print(f"  Sites modelled : {list(combat_model['SITE_labels'])}")
print(f"  Harmonized shape: {X_tr_cb_h.shape}")

# Reconstruct full training array (300_train cases, not just the ~210 ComBat ones)
X_train_h = reconstruct_full_array(X_train, X_tr_cb_h, mask_tr)

print(f"Per-site feature mean BEFORE harmonization (train, first feature):")
for site in sorted(COMBAT_SITES):
    idx = sc_train == site
    if idx.sum() > 0:
        print(f"  {site:<12} : {X_train[idx, 0].mean():.4f}")

print(f"Per-site feature mean AFTER harmonization (train, first feature):")
for site in sorted(COMBAT_SITES):
    idx = sc_train == site
    if idx.sum() > 0:
        print(f"  {site:<12} : {X_train_h[idx, 0].mean():.4f}")

"""# Apply saved ComBat estimates to val and test (transform only — no re-fitting)"""

print("Applying ComBat to val and test (transform only) ...")
def apply_to_split(X_split, sc_split, y_split, mask_split, split_name):
    """
    Apply the fitted combat_model to the ComBat-eligible cases in a split,
    then reconstruct the full array with passthrough cases unchanged.
    """
    if mask_split.sum() == 0:
        print(f"  {split_name}: no ComBat-eligible cases — returned unchanged.")
        return X_split.copy()

    X_cb   = X_split[mask_split]
    sc_cb  = sc_split[mask_split]
    y_cb   = y_split[mask_split]

    covars = pd.DataFrame({
        "SITE": sc_cb,
        "PDAC": y_cb.astype(int),
    })

    X_cb_h = harmonizationApply(X_cb.copy().astype(np.float64),
                                 covars, combat_model)

    X_full_h = reconstruct_full_array(X_split, X_cb_h, mask_split)
    print(f"  {split_name}: harmonized {mask_split.sum()} cases, "
          f"passthrough {(~mask_split).sum()} cases → shape {X_full_h.shape}")
    return X_full_h

X_val_h  = apply_to_split(X_val,  sc_val,  y_val,  mask_va, "Val")
X_test_h = apply_to_split(X_test, sc_test, y_test, mask_te, "Test")

"""# Final sanity checks"""

print("Sanity checks:")
for name, X_orig, X_harm in [
    ("Train", X_train, X_train_h),
    ("Val",   X_val,   X_val_h),
    ("Test",  X_test,  X_test_h),
]:
    assert X_harm.shape == X_orig.shape, \
        f"{name}: shape changed! {X_orig.shape} → {X_harm.shape}"
    assert not np.isnan(X_harm).any(), \
        f"{name}: NaNs found after harmonization!"
    assert not np.isinf(X_harm).any(), \
        f"{name}: Infs found after harmonization!"
    print(f"  {name}: shape={X_harm.shape}  NaN=0  Inf=0  ✓")

"""# Save harmonized arrays and ComBat model"""

np.save(os.path.join(OUTPUT_DIR, "X_train_harmonized_scenarioB.npy"), X_train_h.astype(np.float32))
np.save(os.path.join(OUTPUT_DIR, "X_val_harmonized_scenarioB.npy"), X_val_h.astype(np.float32))
np.save(os.path.join(OUTPUT_DIR, "X_test_harmonized_scenarioB.npy"), X_test_h.astype(np.float32))

with open(os.path.join(OUTPUT_DIR, "combat_model_scenarioB.pkl"), "wb") as f:
    pickle.dump(combat_model, f)

# Also save the combat masks for reference / auditing
np.save(os.path.join(OUTPUT_DIR, "combat_mask_train_scenarioB.npy"), mask_tr)
np.save(os.path.join(OUTPUT_DIR, "combat_mask_val_scenarioB.npy"),   mask_va)
np.save(os.path.join(OUTPUT_DIR, "combat_mask_test_scenarioB.npy"),  mask_te)

print(f"Saved:")
print(f"  X_train_harmonized.npy  → {X_train_h.shape}  "
      f"({mask_tr.sum()} harmonized + {(~mask_tr).sum()} passthrough)")
print(f"  X_val_harmonized.npy    → {X_val_h.shape}  "
      f"({mask_va.sum()} harmonized + {(~mask_va).sum()} passthrough)")
print(f"  X_test_harmonized.npy   → {X_test_h.shape}  "
      f"({mask_te.sum()} harmonized + {(~mask_te).sum()} passthrough)")
print(f"  combat_model.pkl        → fitted on {mask_tr.sum()} training cases")
print(f"  combat_mask_*.npy       → boolean masks for auditing")

print("SUMMARY Scenario B")
print("=" * 30)
print(f"  Total cases          : {len(y_train)+len(y_val)+len(y_test)}")
print(f"  ComBat-harmonized    : " f"{mask_tr.sum()+mask_va.sum()+mask_te.sum()} "
      f"(Siemens + Toshiba + Philips + GE)")
print(f"  Passthrough unchanged: "
      f"{(~mask_tr).sum()+(~mask_va).sum()+(~mask_te).sum()} "
      f"(Canon + Unknown)")
print(f"  Dropped              : 0  — all cases proceed to Step 4")
print("=" * 30)
print("\nStep 3 complete. Run step4_eda.py next.")

"""Let's check the contents of the `INPUT_DIR` (where Step 2 outputs are stored) and `OUTPUT_DIR` (where Step 3 outputs are stored) to see if any ID-related files are present. This will help us understand what was passed between steps and what was saved by this step."""

print(f"Files in INPUT_DIR ({INPUT_DIR}):")
for filename in os.listdir(INPUT_DIR):
    print(f"  - {filename}")

print(f"\nFiles in OUTPUT_DIR ({OUTPUT_DIR}):")
for filename in os.listdir(OUTPUT_DIR):
    print(f"  - {filename}")